### PR TITLE
Very pleasant styling and a darkmode fix.

### PR DESCRIPTION
**Pull request by oliverpalonkorp**
Sorry I started work on this before you merged the most recent darkmode fix. Therefore it's not quite up to date. Even though the commit history shows I would've changed a lot of lines, I did not. The important changes I made are in the css -variable (styling starting from line 118), and then the cheeky fix on the "default" -object, where "Gimme Some Letters..." was previously. My explanation is below:

The locked in filter should be recognizable from the one that is currently being written. Therefore I used the powerful blue to emphasize that the locked in filter is in fact in use. Also changed the shade of gray because the contrast wasn't accessible. Made the background white (I think it looks more pleasing).

I added some horizontal padding on the bubbles to make the negative space more balanced + added a right margin to create a small gap between each filter for a visually pleasing look.

I also made the font-size the same as in the search text, so that there is no jump between font-sizes when the text is recognized as a filter. Feature is self explanatory. I think this is smoother

### CODE REVIEW

**Comment by oliverpalonkorp** [comment]
I also do find it annoying that written input stops showing up in real time while the script fetches the results – but I couldn't figure out how to fix that quite yet.

**Comment by T-Ev** [comment]
Oooh this looks cool... I am going to merge it in the morning once i get up. Thank you for working on it!

**Comment by T-Ev** [comment]
I took your styling suggestions and moved them to this other PR #14

**Comment by T-Ev** [comment]
Changes are implemented via PR #14

**Pull request closed without merging**
