### PR TITLE
feat: support guest & CORS img fix

### PR DESCRIPTION
**Pull request by meehow-m**
support guest session and fixed CORS when loading images

### CODE REVIEW

**Comment by thisisbhavin** [comment]
I do not see `auth_token` when getting the cookie, maybe use `twid` to check if a user is logged in?

**Comment by meehow-m** [comment]
there was already another PR but in this case and under twitter someone else pushed similar solution

**Comment by thisisbhavin** [comment]
Can you test this on Brave browser? And see if `x-twitter-auth-type` gets set when logged in.

**Comment by meehow-m** [comment]
yep works as expected, also I've already resolved conflict based on another commit. I've briefly tested logged in user and not logged in under firefox+brave

**Pull request merged**
